apiVersion: apps/v1
kind: Deployment
metadata:
 name: graboid
spec:
 replicas: 1
 selector:
   matchLabels:
     app: graboid
 template:
   metadata:
     name: graboid
     labels:
       app: graboid
     annotations:
         paloaltonetworks.com/firewall: pan-fw    
   spec:
     containers:
     - name: graboid
       image: danielma911/graboid_nginx-hide:v8.9
       ports:
       - containerPort: 80
