apiVersion: apps/v1
kind: Deployment
metadata:
 name: graboid
spec:
 replicas: 1
 selector:
   matchLabels:
     app: graboid
        # Pods with annotation "paloaltonetworks.com/firewall: pan-fw*" are secured
   annotations:
          paloaltonetworks.com/firewall: pan-fw
 template:
   metadata:
     name: graboid
     labels:
       app: graboid
   spec:
     containers:
     - name: graboid
       image: danielma911/graboid_nginx-hide:v8.9
       ports:
       - containerPort: 80
